name: nix build
on:
  pull_request:
  # push:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3.0.0

      - name: "Cache: prepare /nix/store"
        run: |
          sudo mkdir -p /nix/store
          sudo chown -R $(whoami) /nix/store

      - name: "Cache /nix/store"
        uses: actions/cache@v2
        env:
          cache-name: tmp4
        with:
          path: |
            /nix/store
          key: ${{ env.cache-name }}-${{ hashFiles('./flake.lock') }}-${{ hashFiles('./flake.nix') }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ env.cache-name }}-${{ hashFiles('./flake.lock') }}-${{ hashFiles('./flake.nix') }}-${{ hashFiles('**/*.cabal') }}
            ${{ env.cache-name }}-${{ hashFiles('./flake.lock') }}-${{ hashFiles('./flake.nix') }}-
            ${{ env.cache-name }}-${{ hashFiles('./flake.lock') }}-
            ${{ env.cache-name }}-

      - name: "Cache: let /nix/store owned by root"
        run: |
          sudo chown -R root /nix/store

      - name: "Install nix"
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: "Build and test"
        run: nix build

      - name: "Build and test (flake)"
        run: nix flake check

      # Since actions/cache@v2 runs as runner, /nix/store should be owned by runner
      - name: "Cache: let /nix/store owned by runner"
        run: |
          sudo chown -R $(whoami) /nix/store
