name: nix build
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      # - name: Install nix
      #   uses: cachix/install-nix-action@v16
      #   with:
      #     nix_path: nixpkgs=channel:nixos-unstable
      #
      - name: Cache install Nix packages
        uses: rikhuijzer/cache-install@v1.0.9
        with:
          key: 1-nix-${{ hashFiles('flake.nix') }}

      - name: Build and test
        run: nix build

      - name: Build and test (flake)
        run: nix flake check
